[package]
name = "test-tracing-allocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloc-track = "0.2.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tracing-flame = "0.2.0"